apiVersion: v2
name: yourss
type: application
version: 0.11.1
appVersion: 0.11.1
description: Simple Youtube browser based on RSS feeds
home: https://github.com/essembeh/YouRSS
maintainers:
  - email: essembeh@users.noreply.github.com
    name: SÃ©bastien MB
sources:
  - https://github.com/essembeh/YouRSS
