apiVersion: v2
name: yourss
type: application
version: 0.8.1
appVersion: 0.8.1
description: Webapp to subscribe to Youtube channels using RSS
home: https://github.com/essembeh/YouRSS
maintainers:
  - email: essembeh@users.noreply.github.com
    name: SÃ©bastien MB
sources:
  - https://github.com/essembeh/YouRSS
